language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - pip install coveralls
script:
  - coverage run $(which pytest) tests
after_success:
  - COVERALLS_REPO_TOKEN=nbfEAjpm9IWcsU37pyGCCjf0gDIjOHY3w coveralls
notifications:
  slack: huy-me:BCHLlgc9Af0IiZUW7PZfQgF4